sink:
  config: {server: 'http://localhost:8080'}
  type: datahub-rest
source:
  config:
    connection: {bootstrap: 'localhost:9092'}
    platform_instance: chrono
    topic_message_map: {affirm-event_bus2-idol-pricing-v1-1.PricingPortalUpdatesMerchantOfferConfigs: affirm.event_bus2.idol.pricing.v1.PricingPortalUpdatesMerchantOfferConfigs}
    topic_patterns:
      allow: [^affirm-event_bus2-idol-pricing-v1-1.PricingPortalUpdatesMerchantOfferConfigs$]
    topic_subject_map: {affirm-event_bus2-idol-pricing-v1-1.PricingPortalUpdatesMerchantOfferConfigs-value: event_bus2/idol/pricing_idol/v1/events.proto}
  type: kafka
