SENTINEL = "MISSING"
SUPPORTED_DBS = ['PROD__US']
NAME_COLS = ['FIRST', 'LAST', 'MIDDLE', 'FIRST_NAME', 'LAST_NAME', 'MIDDLE_NAME', 'FULL_NAME', 'LEGAL_NAME']
DOB_COLS = ['DOB', 'DATEOFBIRTH', 'DATE_OF_BIRTH', 'BIRTHDATE', 'BIRTHDAY', 'DOB_YEAR', 'DOB_MONTH', 'DOB_DAY',
            'AGE']
EMAIL_COLS = ['EMAIL', 'EMAIL_ADDR', 'EMAIL_ADDRESS']
PHONE_COLS = ['CELL', 'TEL', 'PHONE', 'PHONE_NUMBER', 'TELEPHONE']
ADDRESS_COLS = ['ADDRESS', 'BILLING_ADDRESS', 'SHIPPING_ADDRESS',
                'ADDR', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'ZIP_CODE',
                'STREET', 'STREET_ADDRESS', 'STREET_1', 'STREET_2']
SSN_COLS = ['SSN', 'SOCIAL_SECURITY', 'SOCIAL_SECURITY_NUMBER']
MAC_ADDRESS_COLS = ['MAC', 'MAC_ADDRESS']
IP_ADDRESS_COLS = ['IP_ADDRESS', "IP", "IPV6", "IP_V6", 'IPV6_ADDRESS', 'IP_V6_ADDRESS']
ORGANIZATION_COLS = ['COMPANY_NAME', "ORGANIZATION_NAME", "COMPANY"]
